### PR TITLE
Implement "clean" subcommand

### PR DESCRIPTION
**Pull request by thekid**
Implements feature request in #9 

Will mark directories it creates with a `.doget` file and only remove those

### CODE REVIEW

**Comment by mikey179** [comment]
Why the overhead with marking the directories? Wouldn't it be better to use a doget specific directory instead of the common `vendor` then?

**Comment by thekid** [comment]
> Wouldn't it be better to use a doget specific directory instead of the common `vendor` then?

I've also thought about that. Suggestions? `.doget/`, `doget`, `doget_modules`?

**Comment by mikey179** [comment]
`doget_modules` sounds reasonable. Since reading https://plus.google.com/+RobPikeTheHuman/posts/R58WgWwN9jp I'm not that fond of dot files or directories any more, and I'd like to keep `doget` open for other purposes.

**Comment by thekid** [comment]
`doget_modules` was influenced by `node_modules`. @kiesel what do you think?

**Comment by thekid** [comment]
Closing this... we found a better solution

**Pull request closed without merging**
